### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by cbrnrd** [cbrnrd/rise#1]
Feel free to contribute to this repo for the Hacktoberfest event

**Comment by justuseapen** [comment]
this looks cool I'll take a crack at helping out. Is the TODO.txt up to date?

**Comment by cbrnrd** [comment]
@justuseapen yessir. However, the auth stuff is more of a personal thing (the auth server was _really really_ bad) so I'm working on improvements now and going to push it when it's better. The `.keyfile` issue is still a valid TODO.

**Comment by danielcarletti** [comment]
`Limit uploads to 50MB` is this for single file or total? Gonna take this one, will open PR as soon as this is cleared.

I gotta know though, why 50mb limit?

**Comment by danielcarletti** [comment]
@cbrnrd lil help here? :)

**Comment by cbrnrd** [comment]
for the total upload size
